language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t plato28/reactwo-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true plato28/reactwo-test npm test

after_success:
  - docker build -t plato28/multwo-client ./client
  - docker build -t plato28/multwo-nginx ./nginx
  - docker build -t plato28/multwo-server ./server
  - docker build -t plato28/multwo-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push plato28/multwo-client
  - docker push plato28/multwo-nginx
  - docker push plato28/multwo-server
  - docker push plato28/multwo-worker
